# Generated by Django 3.2.4 on 2021-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_profilepic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='userProfilePicture'),
        ),
    ]
