# Generated by Django 3.2.4 on 2021-09-04 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guest', '0004_alter_profilepic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddroomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4, verbose_name='title')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='conatact')),
                ('for_rent', models.CharField(max_length=20)),
                ('water_suplly', models.CharField(blank=True, max_length=20, null=True)),
                ('kitchen', models.CharField(blank=True, max_length=20, null=True)),
                ('washroom', models.CharField(blank=True, max_length=20, null=True)),
                ('parking_space', models.CharField(blank=True, max_length=20, null=True)),
                ('troom', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('nearest_city', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('desc', models.CharField(default='', max_length=700)),
                ('rmg1', models.ImageField(default='image1.jpg', upload_to='roomImages')),
                ('rmg2', models.ImageField(default='image2.jpg', upload_to='roomImages')),
                ('rmg3', models.ImageField(default='image3.png', upload_to='roomImages')),
                ('agreement', models.FileField(blank=True, null=True, upload_to='roomAgreement')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
