# Generated by Django 3.2.4 on 2021-09-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_addroommodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroommodel',
            name='agreement',
            field=models.FileField(blank=True, default='default_agreement.pdf', null=True, upload_to='roomAgreement'),
        ),
    ]
