# Generated by Django 3.2.4 on 2021-09-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_alter_addroommodel_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroommodel',
            name='agreement',
            field=models.FileField(default='default_agreement.pdf', upload_to='roomAgreement'),
        ),
    ]
