# Generated by Django 3.2.4 on 2021-09-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0007_alter_addroommodel_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroommodel',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='addroommodel',
            name='pincode',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addroommodel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='addroommodel',
            name='troom',
            field=models.PositiveIntegerField(),
        ),
    ]
