# Generated by Django 3.2.4 on 2021-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_auto_20210907_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroommodel',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
