# Generated by Django 3.2.4 on 2021-09-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_alter_addroommodel_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addroommodel',
            old_name='water_suplly',
            new_name='water_supply',
        ),
    ]
