# Generated by Django 3.2.4 on 2021-09-08 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0011_auto_20210907_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('Below Average', 'Below Average'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('explain_experience', models.CharField(max_length=220)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('addroommodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.addroommodel')),
            ],
        ),
    ]
