# Generated by Django 3.2.4 on 2021-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0012_guestreviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestreviews',
            name='experience',
            field=models.CharField(choices=[('Below Average', 'Below Average'), ('Average', 'Average'), ('Good', 'Good'), ('Better', 'Better'), ('Excellent', 'Excellent')], max_length=50),
        ),
    ]
